name: Build & Deploy Docs (EN + ZH)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pip"

      - name: Install doc dependencies
        run: |
          python -m pip install --upgrade pip
          pip install sphinx sphinx-intl sphinx-rtd-theme myst-parser

      - name: Build docs (EN & ZH)
        working-directory: docs
        run: |
          # 1) 提取原文模板并更新中文 PO
          sphinx-build -b gettext source source/locale
          sphinx-intl update -p source/locale -l zh_CN

          # 2) 构建英文 & 中文到统一站点目录
          sphinx-build -b html -D language=en    source build/site/en
          sphinx-build -b html -D language=zh_CN source build/site/zh

          # 3) 顶层导航页 + .nojekyll 防止 Pages 误当 Jekyll 处理
          mkdir -p build/site
          cat > build/site/index.html <<'HTML'
          <!doctype html><meta charset="utf-8">
          <title>algolib docs</title>
          <h1>algolib documentation</h1>
          <ul>
            <li><a href="en/index.html">English</a></li>
            <li><a href="zh/index.html">简体中文</a></li>
          </ul>
          HTML
          touch build/site/.nojekyll

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/build/site

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4